// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amcgfwzgekzbwdlhzktp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtY2dmd3pnZWt6YndkbGh6a3RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNjk5ODAsImV4cCI6MjA3MzY0NTk4MH0.NMjyHxQeIESimPfX7Ug5xnJkXpeyuyxVkWJP4FtA-NE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});